exports.up = knex => knex.schema.createTable('posts', t => {
  t.string('id').primary()
  t.string('title')
  t.string('link')
  t.text('body')
  t.boolean('enabled').notNullable().defaultTo(true)
  t.boolean('deleted').notNullable().defaultTo(false)
  t.integer('replyCount').unsigned().defaultsTo(0)
  t.string('accountId').notNullable()
  t.string('threadId')
  t.string('parentId')
  t.timestamps(true, true)
})

exports.down = knex => knex.schema.dropTable('posts')
