name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # services:
    #   postgres:
    #     image: postgres:12.3
    #     env:
    #       POSTGRES_DB: postgres
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: gettinPlayed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Supabase
        run: yarn supabase start
      - name: Init DB
        run: PGPASSWORD=postgres psql -h localhost -U postgres < db/schema.sql
      - name: Test
        run: yarn test
