name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # services:
    #   postgres:
    #     image: postgres:12.3
    #     env:
    #       POSTGRES_DB: postgres
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: gettinPlayed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Supabase
        run: docker-compose --file .supabase/docker/docker-compose.yml --project-name supabase up -d
      - name: Init DB
        run: PGPASSWORD=postgres psql -h localhost -p 5435 -U postgres < db/schema.sql
      - name: Test
        run: yarn test
      - name: Capture Log
        if: ${{ failure() || cancelled() }}
        run: docker-compose --file .supabase/docker/docker-compose.yml logs > compose.log
      - name: Upload Artifacts
        if: ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: compose-${{ github.run_id }}
          path: compose.log
